### PR TITLE
Makes metadata write more atomic-like

### LINKED ISSUE #115: DB corrupted on column config partial writes
When writing only a part of a column configuration, the DB gets corrupted:

To reproduce with #113:
```rust
	#[test]
	fn test_from_fuzzer() {
		crate::set_number_of_allowed_io_operations(4);
		let tmp = tempdir().unwrap();
		let mut options = Options::with_columns(tmp.path(), 1);
		options.columns[0].btree_index = true;
		assert!(Db::open_or_create(&options).is_err()); //It's failing because of I/O limit
		Db::open_or_create(&options).unwrap(); //It's going to fail again with 'Column config mismatch'
	}
```

### PR DESCRIPTION
**Pull request by Tpt**
There is still two I/O operations (create + write_all) and write_all might also do multiple operations...

Closes #115

### CODE REVIEW

File: src/options.rs [hunk 1]
```diff
@@ -175,13 +167,14 @@ impl Options {
...
-		writeln!(file, "salt={}", hex::encode(salt))?;
+		let mut metadata = vec![
+			format!("version={}", version.unwrap_or(CURRENT_VERSION)),
+			format!("salt={}", hex::encode(salt)),
+		];
 		for i in 0..self.columns.len() {
-			writeln!(file, "col{}={}", i, self.columns[i].as_string())?;
+			metadata.push(format!("col{}={}", i, self.columns[i].as_string()));
 		}
+		std::fs::write(path, metadata.join("\n"))?;
```
Comment (arkpar) [inline src/options.rs:177]: Hmm, this is still not guaranteed to be atomic, is it? Looking at the documentaion, this calls `std::io::File::write` in a loop, which may result in a file written only partially. TBH I don't think this is likely to cause any issues in the real world. All of the metadata is likely to fit into a single 4kb IO page anyway.

**Review by arkpar — APPROVED** [review]

**Review by cheme — APPROVED** [review]
